version: '3'
services:
  mysql57:
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: pftwitter
      MYSQL_USER: developer
      MYSQL_PASSWORD: devpass
    volumes:
      - ./mysql/data:/var/lib/mysql
